### PR TITLE
8775 homepage next gen images

### PR DESCRIPTION
**Pull request by brianpetway**
https://federal-spending-transparency.atlassian.net/browse/DA-8775

### CODE REVIEW

**Review by anjenkin — CHANGES_REQUESTED** [review]
Colleges and Universities is still using the PNG
R&D animation should use the webp but is still using the gif

Screen Shot 2021-03-17 at 10 19 42 AM

**Comment by brianpetway** [comment]
Changes requested above have been addressed. Ready to review.

**Comment by anjenkin** [comment]
Looks good but one last thing.  I had to add playsInline={true} to the source element for the video to replay after refreshing the page.

**Comment by anjenkin** [comment]
Merging as is.  This works as is when creating a production build.

**Pull request merged**
