### PR TITLE
8763 covid copy refresh

### PR DESCRIPTION
**Pull request by brianpetway**
https://federal-spending-transparency.atlassian.net/browse/DA-8763

### CODE REVIEW

**Comment by anjenkin** [comment]
(1) **Social Share Copy** 
is "Head over to #DataLab to view our newest analysis, The Federal Response to COVID-19"

Should be "Head over to #DataLab to view The Federal Response to COVID-19."


(2) Missing comma in last paragraph of viz1
is "The American Rescue Plan Act, CARES Act and "
should be "
image"


(3) Section three text -  In the section header, the first sentence starts with "Eighty-Four percent" and the f in four should be lowercase

(4) In section three body copy, Department is missing from these terms
is current - "Eighty-Four percent of the $4.5 trillion in COVID-19 funding was appropriated to four agencies: Dept. of the Treasury, Small Business Administration, Dept. of Labor, and the Health & Human Services."

What’s in the MAC - 
"
image"



(5) Section. Three first viz heading should be "Net Agency Funding" instead of "New Agency Funding".  This text is in all of the law summary modals too

(6) DSM
Remove period after this bullet under ‘Total Estimated Lending and Utilization’
* Total credit made available for the Federal Reserve Emergency Lending Facilities is based on the outstanding loans for each of the facilities. As of December 31, 2020 the Federal Reserve Bank (FRB) returned the unobligated funds to Treasury for these programs and closed the program.

Add s to appropriations in this bullet under 'Calculating total spending'
Is "After appropriation warrants are issued"
should be “After appropriations warrants are issued “

**Review by anjenkin — CHANGES_REQUESTED** [review]
See comment above

**Comment by brianpetway** [comment]
I corrected the typos pointed out and added the new yml with the 'Eighty-four' corrected. But Sabrina said the MAC was wrong on the 'Department' instances so those were not changed in the yml.
Ready to review again.

**Comment by anjenkin** [comment]
Looks good for the most part though I initially missed some of the alt text and there's text in the Law Summary modals that still needs to be changed.

Section #1, viz C Total Estimated Value of Legislation
 
Current text - Bar chart of the total estimated value of legislation ($11.25T), which include New Agency Funding ($4.5T) and Tax Relief ($6.75T).
 
Should Be - 
Bar chart of the total estimated value of legislation ($11.25{legislationvalue_trill}T), which includes Net Agency Funding ($4.5 {netbudgetresources}T) and Tax Relief $6.75{taxrelief_trillion}T).
 
Section #2 Alt Text
Missing commas
 
Should be - 
Process flow diagram of COVID-19 supplemental funding, from appropriations to obligations, and ending with outlays.
 
Section #3 
In the Law Summary modals, the heading "New Agency Funding" should be replaced with "Net Agency Funding" (just let me know if this was already taken care of with the Law Summary modal tickets)

**Comment by brianpetway** [comment]
Those corrections have been made. Ready to review again.

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
