### PR TITLE
5900 ie show mes

### PR DESCRIPTION
**Pull request by brett-varney**
https://federal-spending-transparency.atlassian.net/browse/DA-5900

fixes "Show Me" pop-ups for IE11 on AFG home; just needed polyfill for .closest()

NOTE: I cannot "build" this locally, so please check if it's just me, or if this technique needs a tweak

### CODE REVIEW

**Comment by anjenkin** [comment]
@brett-varney Hey, just wondering why you can't build this locally?

**Comment by brett-varney** [comment]
> 
> 
> @brett-varney Hey, just wondering why you can't build this locally?

Me too; just keep throwing an error about a missing image file that I can't get past. Did you get it too?

**Comment by anjenkin** [comment]
@brett-varney This is the error I'm getting when building - 
Building static HTML failed
See our docs page for more info on this error: https://gatsby.dev/debug-html
ReferenceError: Element is not defined

The error is specific to this branch
https://gatsby.dev/debug-html should help you fix this error

**Comment by brett-varney** [comment]
@anjenkin Fixed, builds and works now

**Comment by anjenkin** [comment]
great, looking again

**Pull request merged**
