### PR TITLE
8453 rd section1 svgs

### PR DESCRIPTION
**Pull request by brianpetway**
https://federal-spending-transparency.atlassian.net/browse/DA-8453

Some of the donuts aren't drawing correctly, and I think that is an svg issue rather than a dev issue, but I'm hoping you can confirm.
And should we update the Legend in section 1 to include the purple color for Covid?

### CODE REVIEW

**Comment by anjenkin** [comment]
Good questions, the legend should be removed.  It no longer needed with the new chart design

**Comment by anjenkin** [comment]
Also, I don't see a problem with svgs.  Matt ran into this problem.  He had to include the svgs using the image tag instead of as a svg.  Including the svg using the img tag is preferred for accessibility anyway.

**Comment by anjenkin** [comment]
@brianpetway Hey sorry, I just noticed that the breakpoints are wrong for this section.  I believe they've been wrong for a while.  desktop is 992+, tablet is 768 - 991 and mobile is < 768

Example of the breakpoints being off - 
Screen Shot 2021-02-11 at 10 53 38 AM

**Comment by brianpetway** [comment]
Changed the breakpoints.

**Comment by anjenkin** [comment]
Ok, one last thing - the svg is centered in zeplin on mobile and tablet.

**Comment by brianpetway** [comment]
Good catch on the centering. 
It also allowed me to remove a bunch of unneeded css for the old svg popups and things.
But now, because of the way the svgs are designed, they actually look kind of off center at tablet and phone sizes.
We may want to tweak the positioning to make them appear more symmetrical.

**Comment by anjenkin** [comment]
Oh good.  I'm not seeing the svg centered though??  This is what I'm seeing locally

Screen Shot 2021-02-16 at 10 35 54 PM

I changed the styles on the container like so in dev tools and this looks more centered (even though i do see what you're saying about it still looking a little off).  

Screen Shot 2021-02-16 at 10 35 31 PM

**Comment by brianpetway** [comment]
I changed the svg-container css to what you suggested, rather than the story-section alignLeft class; this way the css only applies to this svg on this page, and not everywhere the story module alignLeft class is applied.
For some reason the code I had before was centering it on iPad and larger phone screens but not the iPhone 6/7/8 screen, which I should've been using to test bc that's what you said to use.

**Review by anjenkin — APPROVED** [review]

**Comment by brianpetway** [comment]
Merged dev in and resolved conflicts.

**Pull request merged**
