### PR TITLE
replace FA icon with svg

### PR DESCRIPTION
**Pull request by brett-varney**
https://federal-spending-transparency.atlassian.net/browse/DA-6094

Show entire close icon on bubble tips

### CODE REVIEW

**Comment by anjenkin** [comment]
@brett-varney There are a bunch of AFG files in this branch that should be unrelated

**Comment by anjenkin** [comment]
@brett-varney Also, to close the tooltip I'm wondering we can't select the tooltip elements and use d3-tipe.hide() to close?

It just makes it confusing that we're using different methods to close these throughout the feature.

**Comment by anjenkin** [comment]
Look this - tooltipClose.click(function () {
	tip.hide();
});

**Comment by brett-varney** [comment]
> 
> 
> @brett-varney There are a bunch of AFG files in this branch that should be unrelated

Correct, all static, so they don't matter

**Comment by brett-varney** [comment]
> 
> 
> const tooltipClose = $('.bubble-detail__close');
> tooltipClose.click(function () {
> tip.hide();
> });
> 
> Like this in the legacy app

If you can figure out how to use it in this instance, I'll approve your update.

**Comment by anjenkin** [comment]
We've run into problems with undetected merge conflicts and these static afg files in the past.  There are have been afg updates made since this PR was opened.

**Comment by anjenkin** [comment]
I see what you mean about the tooltip close.  It would take more time than it's worth to figure out why tip.hide() isn't work especially since we're planning to refactor tooltips.  It's something different about the code being in a React component vs what we were doing in the Jekyll app.  So the approach in this PR is fine.  But we now have a bunch of conflicts with the afg files. I'll merge once the conflicts are resolved; ie. these files are removed from the PR.

**Comment by brett-varney** [comment]
> 
> 
> We've run into problems with undetected merge conflicts and these static afg files in the past. There are have been afg updates made since this PR was opened. That would be great if you could remove them to prevent future problems.

done

**Comment by anjenkin** [comment]
merge conflicts resolved.  merging now...

**Pull request merged**
