### PR TITLE
Fixed issue with loading Competition in Contracting page and items not showing in Contract Explorer

### PR DESCRIPTION
**Pull request by anjenkin**
Issues addressed:
- The Competition in Contracting page not loading in QAT.  
- Build issue Matthew reported due to use of Array.flat() - https://data-transparency-bfs.slack.com/archives/CHSNYBYQP/p1583186762007500
- https://federal-spending-transparency.atlassian.net/browse/DA-5472

I logged a separate ticket to address the issue with the Contract Explorer not loading in IE  https://federal-spending-transparency.atlassian.net/browse/DA-5933

### CODE REVIEW

**Comment by xjackk** [comment]
checkin dis out

**Comment by xjackk** [comment]
@anjenkin Working on FF/Chrome, not working in IE11. Throwing lots of errors

**Comment by xjackk** [comment]
@anjenkin 
ie11-errors-contract

**Comment by anjenkin** [comment]
@xjackk I made a slight change that helps a lot with perf.  I logged a separate ticket for the IE issue to address next sprint.  So this PR should fix the Competition in Contracting issue and the IE build issue.

**Pull request closed without merging**
