### PR TITLE
8730 - Reduce the number of components that use d3v4

### PR DESCRIPTION
**Pull request by anjenkin**
https://federal-spending-transparency.atlassian.net/browse/DA-8730

### CODE REVIEW

**Comment by brianpetway** [comment]
The Glossary is not functioning in the feature branch. It opens but it doesn't go to any page for any entry and typing in the search bar doesn't narrow down the list of entries that is shown.

Is there a way for us to test DTS locally? I don't know of a way to make the DTS data load in a local instance.

There are several lines commented out in
dts.jsx
bar-chart-renderer.jsx
mapViz,jsx
treemap.jsx

**Comment by anjenkin** [comment]
Fixed.  Also the commented out code is a step toward removing places where we're loading in the whole d3v4 library.  It took a while to figure out what was needed to replace that in those places so i didn't want to delete teh code.

**Comment by brianpetway** [comment]
That makes sense about the commented out lines.

I got the DTS to function by moving the dts dir into the public folder like you said, and it looks good.

The Glossary is now successfully showing items when they're clicked on, but the search is still not working.

And there is a console.log left in at dts-tile.jsx, line 56.

**Comment by anjenkin** [comment]
fixed glossary search and removed console log

**Pull request merged**
