### PR TITLE
9812 covid copy final

### PR DESCRIPTION
**Pull request by brianpetway**
https://federal-spending-transparency.atlassian.net/browse/DA-9812

### CODE REVIEW

**Comment by anjenkin** [comment]
Social share text should be updated to - "Interested in learning about #COVID19 supplemental funding? Head over to #DataLab to view The Federal Response to COVID-19. #OpenData #Transparency https://datalab.usaspending.gov/federal-covid-funding/"

**Review by anjenkin — CHANGES_REQUESTED** [review]
See comments inline.  Also there is a merge conflict

**Comment by brianpetway** [comment]
Merges conflicts resolved.

For your first comment, could you specify a line number? Because I'm seeing that Share content in budget.jsx line 238 and line 250. And that content comes up when clicking 'Share' and 'email' - which is the only one I can check on my machine.

And for the second one - that footnote is deleted, along with the line preceding it. Yesterday Alicia and Kelli confirmed that the only footnote is now located in the 'How Do You Track...' accordion, and it was new in this update.

**Comment by brianpetway** [comment]
I had missed the change in the Share copy, that was the issue. My eyes didn't catch the three words that were removed from it.
Updated now.

**Comment by brianpetway** [comment]
#3 and #4 have been corrected.
Ready to review again.

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
