### PR TITLE
8537 - Fixed the mobile and tablet thresholds to determine which section is active

### PR DESCRIPTION
**Pull request by anjenkin**
https://federal-spending-transparency.atlassian.net/browse/DA-8537

* Fixed mobile and tablet issues found while testing DA-8537
* Also, fixed how we're detecting is mobile.  The DL breakpoints are different than AFG so we can't use the isMobileDevice helper in the AFG code.  DL has a helper checkScreenMode to determine if we're in desktop, tablet or mobile.

### CODE REVIEW

**Comment by brianpetway** [comment]
At tablet size there is now a white border visible between the label and the arrow element when clicking (tapping) on a circle.
At phone size the arrow is appearing on the wrong side of the label, and that white border is also visible.

**Comment by brianpetway** [comment]
Please disregard those earlier comments.
Those behaviors appeared with the previous toc circles ticket, 8636, and the comments should go on that pr.

**Comment by anjenkin** [comment]
I logged a new ticket to address the two issues above (1) the white line between the label and the arrow and (2) the arrow on the wrong side in tablet since those issues can be reproduced in QAT. The code changed for this ticket shouldn't relate to the label or the placement of the arrow. https://federal-spending-transparency.atlassian.net/browse/DA-8669

**Comment by brianpetway** [comment]
After merging 8636 into dev, this one now has conflicts that need to be resolved.

**Pull request merged**
