### PR TITLE
6076 homepage mobile spacing

### PR DESCRIPTION
**Pull request by brett-varney**
https://federal-spending-transparency.atlassian.net/browse/DA-6076

### CODE REVIEW

**Comment by anjenkin** [comment]
@brett-varney @xjackk Please don't delete the stacked vs side by side secondary panels.  Both work and with new analyses coming soon we may need to go back to the old format.  Thank you.

**Comment by brett-varney** [comment]
> 
> 
> @brett-varney @xjackk Please don't delete the stacked vs side by side secondary panels. Both work and with new analyses coming soon we may need to go back to the old format. Thank you.

OK, why won't this work in both cases?

**Comment by anjenkin** [comment]
I didn't look at the new code so if it's designed to show either 1 analysis like we current have on the homepage and also work for 2 analyses like we previously had and what's in the R & D mocks, that's great.  Otherwise we need to keep stacked and side by side.  Stacked was intended for 1 analysis like we currently have.  side by side was designed for 2 analyses like the R & D homepage below.
Screen Shot 2020-04-08 at 10 59 49 AM

**Comment by brett-varney** [comment]
@anjenkin restored side-by-side files

**Comment by anjenkin** [comment]
@brett-varney 
Looks good.  I just found a few issues:
1) the Homelessness section doesn't match the mock on mobile or tablet.  QAT matches the mock for homelessness on mobile and tablet.

In the screenshots, the right side is the expected behavior.

MOBILE
Screen Shot 2020-04-09 at 10 33 51 AM

TABLET
Screen Shot 2020-04-09 at 10 32 10 AM

2) Extra space at the top of page is missing on tablet

Screen Shot 2020-04-09 at 10 20 06 AM

**Comment by brett-varney** [comment]
@anjenkin addressed noted concerns

**Pull request merged**
