### PR TITLE
dts date fix

### PR DESCRIPTION
**Pull request by xjackk**
* https://federal-spending-transparency.atlassian.net/browse/DA-6057

After poking around for a day, the fix was of course simple!

This whole timestamp thing we were appending to the date was unnecessary. We just had to mirror what we were doing in `prod`.

`prod` has a function being called on the `d3.csv` read in called `type` that calls the d3 function: `d3.timeParse("%Y-%m-%d")` on it. This mirrors how we do it on `prod` one to one.

### CODE REVIEW

**Comment by anjenkin** [comment]
@xjackk Does this need to be applied to the homepage DTS widget too?

**Comment by anjenkin** [comment]
Double checked.  The fix looks good we just need to apply it to the homepage DTS widget too.

**Comment by xjackk** [comment]
Yeah probably does, will do that real fast now @anjenkin

**Comment by xjackk** [comment]
@anjenkin it does that even with mock data, im not sure why. Im fairly certain pushing this to `qat` it will work.

**Pull request merged**
