### PR TITLE
5838 show tables in ie

### PR DESCRIPTION
**Pull request by brett-varney**
https://federal-spending-transparency.atlassian.net/browse/DA-5838

Basically I just removed the extra container-wrappers for these two tables, since the one that worked didn't have it. My only guess is that the object ref was getting lost in the extra wrap.

Note that for some reason Homeless map used the bubble chart's container, so I had to remove that as well.

Note also that I'm getting occasional weird errors testing locally, so I'm not 100% confident this works, or why it may fail. I hope this is just my testing.

### CODE REVIEW

**Comment by xjackk** [comment]
im workin in IE in a little bit so i'll check this out ~

**Comment by xjackk** [comment]
@brett-varney Can confirm that the section 3 table is working well but the section 4 table is taking up the space when toggled, but just showing the pagination bar at the bottom.

**Comment by brett-varney** [comment]
> 
> 
> @brett-varney Can confirm that the section 3 table is working well but the section 4 table is taking up the space when toggled, but just showing the pagination bar at the bottom.

Thanks, more drawing board...

**Comment by brett-varney** [comment]
> 
> 
> @brett-varney Can confirm that the section 3 table is working well but the section 4 table is taking up the space when toggled, but just showing the pagination bar at the bottom.

@xjackk Finally works for me now

**Pull request merged**
