### PR TITLE
Fix IE nav bug

### PR DESCRIPTION
**Pull request by mattforjan**
no ticket

### CODE REVIEW

**Comment by anjenkin** [comment]
The Resources mega menu items are shifted to the right in this branch -
 
Screen Shot 2020-11-20 at 1 21 53 PM

**Comment by mattforjan** [comment]
> The Resources mega menu items are shifted to the right in this branch -

I think this is how it is normally - it looks like this in QAT as well
Screen Shot 2020-11-20 at 1 37 03 PM

**Comment by anjenkin** [comment]
Yeah, I think it was introduced when the About Us link was added.  The mega menu items are left aligned with "Resources" PROD - 
Screen Shot 2020-11-20 at 1 40 06 PM. 

I could ask Kelli to log a separate ticket if necessary.

**Comment by mattforjan** [comment]
no that's alright, just fixed it

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
