### PR TITLE
added toc hover color

### PR DESCRIPTION
**Pull request by anjenkin**
https://federal-spending-transparency.atlassian.net/browse/DA-5737

### CODE REVIEW

**Comment by anjenkin** [comment]
Can you send a screenshot of the different layout?

**Comment by anjenkin** [comment]
Any layout change wasn't intentional

**Comment by brett-varney** [comment]
> 
> 
> Any layout change wasn't intentional

My guess is they changed they layout without telling us explicitly, so this is still the "old, previously correct" layout. I just noticed differences from the ticket's screen.

**Comment by anjenkin** [comment]
@brett-varney The requirements in the ticket have been clarified.  And I've made the requested updates.

**Pull request merged**
