### PR TITLE
8537 - Fixed Intersection Observer for TOC circles nav

### PR DESCRIPTION
**Pull request by anjenkin**
https://federal-spending-transparency.atlassian.net/browse/DA-8537

### CODE REVIEW

**Comment by brianpetway** [comment]
- The Zeplin mocks show the circles on the left side at tablet size, but this branch has them on the right; I may be looking at the wrong mocks, or old ones, but there's no link to mocks in the ticket
- The AC says the color should change and the badge should show on hover
- When you are at the bottom of the page, in section 3, and use the button at lower right to return to top, when you get to the top the section 3 badge is still highlighted, and stays highlighted until you scroll down into section 1 - this isn't in the AC so may be an enhancement

**Comment by anjenkin** [comment]
@brianpetway The Zeplin mocks for the Chapter Release and R & D show the circles on the left - https://app.zeplin.io/project/5d2f7049581d618dfb0019fe/screen/5fe34d5e62a35699a7607e7b. Can you point me to the mock where you saw it on the right?  We may need to reach out to Danielle to update the mock.

Also, the AC for the hover behavior was broken out into ticket - DA-8577 https://federal-spending-transparency.atlassian.net/browse/DA-8577

**Comment by anjenkin** [comment]
Point #3 - Great point.  This warrants it's own ticket as it requires some refactoring.  I logged the following ticket to address this - https://federal-spending-transparency.atlassian.net/browse/DA-8636

**Comment by anjenkin** [comment]
Fixed the TOC position on tablet

**Pull request merged**
