### PR TITLE
8723 - CSS change to scrolling TOC circles to prevent overlap with vizs in R&D

### PR DESCRIPTION
**Pull request by anjenkin**
https://federal-spending-transparency.atlassian.net/browse/DA-8723

### CODE REVIEW

**Comment by brianpetway** [comment]
There are some confusing things about this ticket.

The first AC isn't happening in qat when using the iPad emulator in devTools but it is happening at around 1000px width, because the icons are under the toc circles main-container and they can't be clicked. So it is a problem, but it isn't described clearly in the ticket.
The second AC isn't happening in qat at all any more (I think you fixed that in another ticket?), but similar to the problem at 1000px, at mobile size the icon on the far right of the section 2 chart is under the toc circles container and can't be clicked.

In the 8723 branch - when I ran 'build' the problem of the chart icons under the toc circles main-container being clickable was fixed but at desktop size when I hovered over the toc circles the labels were very faint and barely visible. Then I ran 'develop' and that was no longer happening, the labels were visible on hover, but they were not fading out at all, they disappear instantly when the mouse moves away. But the problem of the chart icons under the toc circles main-container being clickable was fixed. 

I don't know why the behavior would be different when running 'build' and 'develop'.

Also, in the labelContainer class you have both 'display: flex' and "display: none'.

**Comment by anjenkin** [comment]
Fixed, I removed the right margin for desktop and tablet and then removed the left margin on mobile.  I think that's about the smallest we can make the hit area for the circles.  Also, I replace the display: flex / display: none with z-index since display is not an animatable property.

**Comment by brianpetway** [comment]
Using z-index solved the issue, but changing the margins for the circles moved the labels, so in mobile they are too close to the circles and in tablet and desktop they are a little further away than they were before.

**Comment by brianpetway** [comment]
Merging this in. We'll make a new ticket for the hover problem in production build.

**Pull request merged**
